begin;

create schema if not exists app_private;

create or replace function app_private.touch_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function app_private.prevent_audit_log_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  raise exception 'audit_log is append-only';
end;
$$;

create or replace function app_private.enforce_payroll_sod()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_preparer uuid;
begin
  select prepared_by_user_id
    into v_preparer
    from public.payroll_runs
   where id = new.payroll_run_id;

  if not found then
    raise exception 'payroll run % not found', new.payroll_run_id;
  end if;

  if v_preparer = new.approver_user_id then
    raise exception 'Segregation of duties violation: payroll preparer cannot approve the same payroll run';
  end if;

  return new;
end;
$$;

create or replace function app_private.enforce_wire_transfer_sod()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_initiator uuid;
begin
  select initiated_by_user_id
    into v_initiator
    from public.wire_transfers
   where id = new.wire_transfer_id;

  if not found then
    raise exception 'wire transfer % not found', new.wire_transfer_id;
  end if;

  if v_initiator = new.approver_user_id then
    raise exception 'Segregation of duties violation: wire transfer initiator cannot authorize the same transfer';
  end if;

  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  email text not null unique,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_roles (
  user_id uuid not null references public.users (id) on delete cascade,
  role_id uuid not null references public.roles (id) on delete cascade,
  assigned_by_user_id uuid references public.users (id) on delete set null,
  assigned_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, role_id)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.users (id) on delete set null,
  entity_table text not null,
  entity_id text not null,
  action text not null check (action in ('insert', 'update', 'delete', 'approve', 'reject', 'sync', 'login')),
  before_state jsonb,
  after_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  client_code text not null unique,
  legal_name text not null,
  billing_email text,
  phone text,
  status text not null default 'active' check (status in ('active', 'inactive', 'prospect')),
  account_manager_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients (id) on delete restrict,
  location_code text not null unique,
  name text not null,
  address_line_1 text,
  address_line_2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text not null default 'US' check (char_length(country_code) = 2),
  timezone_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  project_code text not null unique,
  client_id uuid not null references public.clients (id) on delete restrict,
  location_id uuid references public.locations (id) on delete set null,
  name text not null,
  description text,
  status text not null default 'planned' check (status in ('planned', 'active', 'on_hold', 'completed', 'cancelled')),
  start_date date,
  end_date date,
  budget_amount numeric(14,2),
  project_manager_user_id uuid references public.users (id) on delete set null,
  created_by_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_number text not null unique,
  user_id uuid unique references public.users (id) on delete set null,
  manager_employee_id uuid references public.employees (id) on delete set null,
  first_name text not null,
  last_name text not null,
  work_email text,
  department text not null,
  job_title text not null,
  employment_status text not null default 'active' check (employment_status in ('active', 'leave', 'terminated')),
  hire_date date not null,
  termination_date date,
  base_salary numeric(14,2),
  payroll_identifier text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.leave_requests (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees (id) on delete restrict,
  requested_by_user_id uuid not null references public.users (id) on delete restrict,
  leave_type text not null check (leave_type in ('vacation', 'sick', 'personal', 'bereavement', 'unpaid', 'other')),
  start_date date not null,
  end_date date not null,
  total_days numeric(6,2) not null check (total_days > 0),
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected', 'cancelled')),
  reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (end_date >= start_date)
);

create table if not exists public.leave_approvals (
  id uuid primary key default gen_random_uuid(),
  leave_request_id uuid not null references public.leave_requests (id) on delete cascade,
  approver_user_id uuid not null references public.users (id) on delete restrict,
  decision text not null check (decision in ('approved', 'rejected')),
  notes text,
  decided_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (leave_request_id, approver_user_id)
);

create table if not exists public.gwo_certifications (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees (id) on delete cascade,
  certification_type text not null,
  certification_number text,
  issued_on date,
  expires_on date,
  status text not null default 'active' check (status in ('active', 'expired', 'revoked', 'pending_verification')),
  verified_by_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (expires_on is null or issued_on is null or expires_on >= issued_on)
);

create table if not exists public.work_orders (
  id uuid primary key default gen_random_uuid(),
  work_order_number text not null unique,
  project_id uuid not null references public.projects (id) on delete restrict,
  client_id uuid not null references public.clients (id) on delete restrict,
  location_id uuid references public.locations (id) on delete set null,
  title text not null,
  description text,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'in_progress', 'completed', 'cancelled')),
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  created_by_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.work_order_assignments (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders (id) on delete cascade,
  employee_id uuid not null references public.employees (id) on delete restrict,
  assigned_by_user_id uuid references public.users (id) on delete set null,
  assignment_role text not null,
  assigned_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (work_order_id, employee_id)
);

create table if not exists public.expense_claims (
  id uuid primary key default gen_random_uuid(),
  claim_number text not null unique,
  employee_id uuid not null references public.employees (id) on delete restrict,
  submitted_by_user_id uuid not null references public.users (id) on delete restrict,
  expense_date date not null,
  amount numeric(14,2) not null check (amount > 0),
  currency_code text not null default 'USD' check (char_length(currency_code) = 3),
  category text not null,
  description text,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected', 'paid', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_approvals (
  id uuid primary key default gen_random_uuid(),
  expense_claim_id uuid not null references public.expense_claims (id) on delete cascade,
  approver_user_id uuid not null references public.users (id) on delete restrict,
  decision text not null check (decision in ('approved', 'rejected')),
  notes text,
  decided_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (expense_claim_id, approver_user_id)
);

create table if not exists public.payroll_runs (
  id uuid primary key default gen_random_uuid(),
  run_code text not null unique,
  period_start date not null,
  period_end date not null,
  payment_date date,
  status text not null default 'draft' check (status in ('draft', 'prepared', 'approved', 'posted', 'void')),
  gross_amount numeric(14,2) not null default 0 check (gross_amount >= 0),
  net_amount numeric(14,2) not null default 0 check (net_amount >= 0),
  prepared_by_user_id uuid not null references public.users (id) on delete restrict,
  finalized_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (period_end >= period_start)
);

create table if not exists public.payroll_approvals (
  id uuid primary key default gen_random_uuid(),
  payroll_run_id uuid not null references public.payroll_runs (id) on delete cascade,
  approver_user_id uuid not null references public.users (id) on delete restrict,
  decision text not null check (decision in ('approved', 'rejected')),
  notes text,
  decided_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (payroll_run_id, approver_user_id)
);

create table if not exists public.wire_transfers (
  id uuid primary key default gen_random_uuid(),
  transfer_number text not null unique,
  initiated_by_user_id uuid not null references public.users (id) on delete restrict,
  beneficiary_name text not null,
  beneficiary_account_last4 text not null check (char_length(beneficiary_account_last4) = 4),
  amount numeric(14,2) not null check (amount > 0),
  currency_code text not null default 'USD' check (char_length(currency_code) = 3),
  purpose text,
  requested_execution_on date,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'authorized', 'released', 'rejected', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.wire_authorizations (
  id uuid primary key default gen_random_uuid(),
  wire_transfer_id uuid not null references public.wire_transfers (id) on delete cascade,
  approver_user_id uuid not null references public.users (id) on delete restrict,
  decision text not null check (decision in ('approved', 'rejected')),
  notes text,
  authorized_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (wire_transfer_id, approver_user_id)
);

create table if not exists public.standing_payments (
  id uuid primary key default gen_random_uuid(),
  payment_reference text not null unique,
  client_id uuid references public.clients (id) on delete set null,
  payee_name text not null,
  amount numeric(14,2) not null check (amount > 0),
  currency_code text not null default 'USD' check (char_length(currency_code) = 3),
  frequency text not null check (frequency in ('weekly', 'biweekly', 'monthly', 'quarterly', 'annually')),
  next_due_on date not null,
  is_active boolean not null default true,
  owner_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.quickbooks_sync_log (
  id uuid primary key default gen_random_uuid(),
  entity_table text not null,
  entity_id uuid,
  external_object_type text not null,
  external_object_id text,
  sync_direction text not null check (sync_direction in ('push', 'pull')),
  sync_status text not null check (sync_status in ('pending', 'success', 'failed')),
  request_payload jsonb,
  response_payload jsonb,
  error_message text,
  synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  client_id uuid not null references public.clients (id) on delete restrict,
  project_id uuid references public.projects (id) on delete set null,
  status text not null default 'draft' check (status in ('draft', 'issued', 'paid', 'void', 'overdue')),
  issue_date date not null,
  due_date date not null,
  subtotal_amount numeric(14,2) not null default 0 check (subtotal_amount >= 0),
  tax_amount numeric(14,2) not null default 0 check (tax_amount >= 0),
  total_amount numeric(14,2) not null default 0 check (total_amount >= 0),
  currency_code text not null default 'USD' check (char_length(currency_code) = 3),
  quickbooks_invoice_id text,
  created_by_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (due_date >= issue_date)
);

create index if not exists idx_user_roles_role_id on public.user_roles (role_id);
create index if not exists idx_clients_account_manager on public.clients (account_manager_user_id);
create index if not exists idx_locations_client_id on public.locations (client_id);
create index if not exists idx_projects_client_id on public.projects (client_id);
create index if not exists idx_projects_location_id on public.projects (location_id);
create index if not exists idx_employees_user_id on public.employees (user_id);
create index if not exists idx_employees_manager_employee_id on public.employees (manager_employee_id);
create index if not exists idx_leave_requests_employee_status on public.leave_requests (employee_id, status);
create index if not exists idx_leave_approvals_request_id on public.leave_approvals (leave_request_id);
create index if not exists idx_leave_approvals_approver_user_id on public.leave_approvals (approver_user_id);
create index if not exists idx_gwo_certifications_employee_expiry on public.gwo_certifications (employee_id, expires_on);
create index if not exists idx_gwo_certifications_verified_by_user_id on public.gwo_certifications (verified_by_user_id);
create index if not exists idx_work_orders_project_status on public.work_orders (project_id, status);
create index if not exists idx_work_orders_client_id on public.work_orders (client_id);
create index if not exists idx_work_orders_location_id on public.work_orders (location_id);
create index if not exists idx_work_orders_created_by_user_id on public.work_orders (created_by_user_id);
create index if not exists idx_work_order_assignments_work_order_id on public.work_order_assignments (work_order_id);
create index if not exists idx_work_order_assignments_employee_id on public.work_order_assignments (employee_id);
create index if not exists idx_work_order_assignments_assigned_by_user_id on public.work_order_assignments (assigned_by_user_id);
create index if not exists idx_expense_claims_employee_status on public.expense_claims (employee_id, status);
create index if not exists idx_expense_claims_submitted_by_user_id on public.expense_claims (submitted_by_user_id);
create index if not exists idx_expense_approvals_claim_id on public.expense_approvals (expense_claim_id);
create index if not exists idx_expense_approvals_approver_user_id on public.expense_approvals (approver_user_id);
create index if not exists idx_payroll_runs_period on public.payroll_runs (period_start, period_end);
create index if not exists idx_payroll_runs_prepared_by_user_id on public.payroll_runs (prepared_by_user_id);
create index if not exists idx_payroll_approvals_run_id on public.payroll_approvals (payroll_run_id);
create index if not exists idx_payroll_approvals_approver_user_id on public.payroll_approvals (approver_user_id);
create index if not exists idx_wire_transfers_status on public.wire_transfers (status);
create index if not exists idx_wire_transfers_initiated_by_user_id on public.wire_transfers (initiated_by_user_id);
create index if not exists idx_wire_authorizations_transfer_id on public.wire_authorizations (wire_transfer_id);
create index if not exists idx_wire_authorizations_approver_user_id on public.wire_authorizations (approver_user_id);
create index if not exists idx_standing_payments_next_due_on on public.standing_payments (next_due_on);
create index if not exists idx_standing_payments_client_id on public.standing_payments (client_id);
create index if not exists idx_standing_payments_owner_user_id on public.standing_payments (owner_user_id);
create index if not exists idx_quickbooks_sync_log_entity on public.quickbooks_sync_log (entity_table, entity_id);
create index if not exists idx_invoices_client_status on public.invoices (client_id, status);
create index if not exists idx_invoices_project_id on public.invoices (project_id);
create index if not exists idx_invoices_created_by_user_id on public.invoices (created_by_user_id);
create index if not exists idx_audit_log_entity on public.audit_log (entity_table, entity_id);
create index if not exists idx_audit_log_actor_created_at on public.audit_log (actor_user_id, created_at desc);
create index if not exists idx_projects_project_manager_user_id on public.projects (project_manager_user_id);
create index if not exists idx_projects_created_by_user_id on public.projects (created_by_user_id);
create index if not exists idx_leave_requests_requested_by_user_id on public.leave_requests (requested_by_user_id);
create index if not exists idx_user_roles_assigned_by_user_id on public.user_roles (assigned_by_user_id);

insert into public.roles (code, name, description)
values
  ('erp_admin', 'ERP Administrator', 'Full ERP administration privileges'),
  ('aida_lead', 'AIDA Lead', 'Owns platform governance and delivery approvals'),
  ('appia_stakeholder', 'Appia Stakeholder', 'Business stakeholder and approver'),
  ('finance_preparer', 'Finance Preparer', 'Prepares expense, payroll, and transfer records'),
  ('finance_approver', 'Finance Approver', 'Approves finance records'),
  ('payroll_preparer', 'Payroll Preparer', 'Prepares payroll runs'),
  ('payroll_approver', 'Payroll Approver', 'Approves payroll runs'),
  ('wire_initiator', 'Wire Initiator', 'Initiates wire transfers'),
  ('wire_authorizer', 'Wire Authorizer', 'Authorizes wire transfers'),
  ('hr_manager', 'HR Manager', 'Manages employees and leave workflows'),
  ('operations_manager', 'Operations Manager', 'Manages projects and work orders')
on conflict (code) do nothing;

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'users',
    'roles',
    'user_roles',
    'audit_log',
    'clients',
    'locations',
    'projects',
    'employees',
    'leave_requests',
    'leave_approvals',
    'gwo_certifications',
    'work_orders',
    'work_order_assignments',
    'expense_claims',
    'expense_approvals',
    'payroll_runs',
    'payroll_approvals',
    'wire_transfers',
    'wire_authorizations',
    'standing_payments',
    'quickbooks_sync_log',
    'invoices'
  ]
  loop
    execute format('alter table public.%I enable row level security', tbl);
    execute format('alter table public.%I force row level security', tbl);
  end loop;
end
$$;

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'users',
    'roles',
    'clients',
    'locations',
    'projects',
    'employees',
    'leave_requests',
    'leave_approvals',
    'gwo_certifications',
    'work_orders',
    'work_order_assignments',
    'expense_claims',
    'expense_approvals',
    'payroll_runs',
    'payroll_approvals',
    'wire_transfers',
    'wire_authorizations',
    'standing_payments',
    'quickbooks_sync_log',
    'invoices'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', tbl, tbl);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function app_private.touch_updated_at()',
      tbl,
      tbl
    );
  end loop;
end
$$;

drop trigger if exists protect_audit_log_from_update on public.audit_log;
create trigger protect_audit_log_from_update
before update on public.audit_log
for each row
execute function app_private.prevent_audit_log_mutation();

drop trigger if exists protect_audit_log_from_delete on public.audit_log;
create trigger protect_audit_log_from_delete
before delete on public.audit_log
for each row
execute function app_private.prevent_audit_log_mutation();

drop trigger if exists enforce_payroll_sod on public.payroll_approvals;
create trigger enforce_payroll_sod
before insert or update on public.payroll_approvals
for each row
execute function app_private.enforce_payroll_sod();

drop trigger if exists enforce_wire_transfer_sod on public.wire_authorizations;
create trigger enforce_wire_transfer_sod
before insert or update on public.wire_authorizations
for each row
execute function app_private.enforce_wire_transfer_sod();

comment on schema app_private is 'Private helper functions for ERP security controls and triggers.';
comment on table public.audit_log is 'Append-only audit ledger. Updates and deletes are blocked by trigger.';
comment on table public.payroll_approvals is 'Payroll approvals are subject to DB-level separation of duties against payroll_runs.prepared_by_user_id.';
comment on table public.wire_authorizations is 'Wire authorizations are subject to DB-level separation of duties against wire_transfers.initiated_by_user_id.';

commit;
